### ISSUE TITLE
Crash after moving focus from multiple focused windows

### ISSUE THREAD

**Issue by Nirlep5252** [outfoxxed/hy3#50] opened 2023-12-10 08:58 UTC
When raising focus and then trying to move focus to a neighbor, Hyprland crashes.

hy3 commit hash: f71ac3756570abf028a4c9fc5a07b58a09ba5072
hyprland commit hash: [`af6aae4`](https://github.com/hyprwm/Hyprland/commit/af6aae4e12b96fff701d8ae8fcb48ea8bb51009f)

Steps to reproduce:
- create more than 1 window
- raise focus
- try to move focus when multiple windows are focused

**Comment by outfoxxed** [comment] 2023-12-10 09:03
Dumb mistake, fixed in b341fe6. I've crashed from it a few times but wasn't able to isolate the cause. Thanks!

**Closed by outfoxxed** 2023-12-10 09:03 UTC

**Comment by Nirlep5252** [comment] 2023-12-10 09:04
Wow, that was fast! Thanks.

**Comment by outfoxxed** [comment] 2023-12-10 09:06
Np. I was around and there was only one likely cause.
